apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  secretObjects:
    - secretName: cosmos-ro #secretKeyRef name in csi
      data:
        - key: cosmos-ro #key in csi
          objectName: CosmosConnectionStringRO
      type: Opaque
    - secretName: cosmos-rw
      data:
        - key: cosmos-rw
          objectName: CosmosConnectionStringRW
      type: Opaque
    - secretName: storage-rw
      data:
        - key: storage-rw
          objectName: StorageConnectionStringRW
      type: Opaque
    - secretName: app-insights
      data:
        - key: app-insights
          objectName: ApplicationInsightsConnectionString
      type: Opaque
    - secretName: iothub-default-endpoint
      data:
        - key: iothub-default-endpoint
          objectName: IoTHubDefaultEndpointConnectionString
      type: Opaque
    - secretName: iothub-device-connection-string
      data:
        - key: iothub-device-connection-string
          objectName: IoTHubDeviceConnectionString
      type: Opaque
    - secretName: google-geolocation-apikey
      data:
        - key: google-geolocation-apikey
          objectName: GoogleGeolocationAPIKey
      type: Opaque
    - secretName: google-geocoding-apikey
      data:
        - key: google-geocoding-apikey
          objectName: GoogleGeocodeAPIKey
      type: Opaque
    - secretName: cario-api-gateway-token
      data:
        - key: cario-api-gateway-token
          objectName: CarioApiGatewayToken
      type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2715e4d3-abf1-4018-b892-8a9600932132"
    keyvaultName: "iot-australiasoutheast" # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: CosmosConnectionStringRO
          objectType: secret
          objectVersion: ""
        - |
          objectName: CosmosConnectionStringRW
          objectType: secret
          objectVersion: ""
        - |
          objectName: StorageConnectionStringRW
          objectType: secret
          objectVersion: ""
        - |
          objectName: ApplicationInsightsConnectionString
          objectType: secret
          objectVersion: ""
        - |
          objectName: IoTHubDefaultEndpointConnectionString
          objectType: secret
          objectVersion: ""
        - |
          objectName: IoTHubDeviceConnectionString
          objectType: secret
          objectVersion: ""
        - |
          objectName: GoogleGeolocationAPIKey
          objectType: secret
          objectVersion: ""
        - |
          objectName: GoogleGeocodeAPIKey
          objectType: secret
          objectVersion: ""
        - |
          objectName: CarioApiGatewayToken
          objectType: secret
          objectVersion: ""
    tenantId: "b6dfe62e-2526-424e-9341-b7d23567d7c2"
