apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-api
  labels:
    app: iot-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-api
  template:
    metadata:
      labels:
        app: iot-api
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: iot-api
      containers:
        - name: iot-api
          image: freightpeople.azurecr.io/iot/iot-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: COSMOS_CONNECTION_STRING #env variable to create
              valueFrom:
                secretKeyRef:
                  name: cosmos-ro
                  key: cosmos-ro
            - name: APPINSIGHTS_INSTRUMENTATIONKEY #env variable to create
              valueFrom:
                secretKeyRef:
                  name: app-insights
                  key: app-insights
            - name: STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: storage-rw
                  key: storage-rw
            - name: CARIO_API_GATEWAY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cario-api-gateway-token
                  key: cario-api-gateway-token
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
---
apiVersion: v1
kind: Service
metadata:
  name: iot-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: iot-api
