name: Build the Sample service

on:
  push:
    branches: [main]
    paths:
      - "src/sample/**"
      - ".github/workflows/build_sample_service.yaml"
  pull_request:
    branches: [main]
    paths:
      - "src/sample/**"
      - ".github/workflows/build_sample_service.yaml"

defaults:
  run:
    working-directory: src/sample

env:
  REGISTRY_NAME: freightpeople.azurecr.io
  CLUSTER_NAME: freightpeople-iot-aks
  CLUSTER_RESOURCE_GROUP: iot-australiasoutheast
  NAMESPACE: eventprocessing
  APP_NAME: iot/sample

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - run: npm ci
      - run: npm run build --if-present

      - name: Test
        run: npm test

      - name: Docker publish
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.sha }} -t ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:latest -t ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:v0.1
          docker push --all-tags ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}

      # Set the target Azure Kubernetes Service (AKS) cluster.
      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      # Create namespace if doesn't exist
      - run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -

      # Deploy app to AKS
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            src/sample/manifests/deployment.yaml
          images: |
            ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}
          namespace: ${{ env.NAMESPACE }}
